### ISSUE TITLE
Frage zur Installation

### ISSUE THREAD

**Issue by Kai9555** [JWThewes/hueshelly#6]
Hi @JWThewes 

ich bin gerade eher zufällig über hueshelly gestolpert. Mir ist leider nicht ganz klar wie ich hueshelly auf einem Raspberry pi (oder erst einmal zum Testen auf macOS) zum laufen bekomme. Ich habe bisher auf GitHub leider nur Berührungspunkte mit Homebridge gehabt und finde mich da zwar Grundlegen sehr gut zurecht, aber damit hört es auch schon auf.

Ich würde mich freuen wenn du dir die Mühe macht und eine kurze verständliche Anleitung schreiben könntest.

Vielen Dank
Kai

By The Way:
In meinem Verteilerkasten habe ich noch die alten Shelly 4 Pro, die kein HTTP Webhook verstehen, hinter denen aber fast nur Hue Lampen hängen. Sollte mein Test mit einem Shelly 1 PM erfolgreich sein, dann würde ich auf die neuen Shelly 4 Pro upgraden.

**Comment by JWThewes** [comment]
Das mache ich gerne fertig. Schaue ob ich am Wochenende dazu komme.

**Comment by JWThewes** [comment]
Den Link hast du aber gesehen: https://github.com/JWThewes/hueshelly/wiki/How-to-use-hueshelly

**Comment by Kai9555** [comment]
Ja den habe ich gesehen. Habe mir auch die Version für macOS (M1) ausgewählt. Im Downloadorder landet dann aber eine nicht typisierte Datei. Mit fehlt hier der Anfang wie ich mit der Datei (später dann aber natürlich am Pi) umgehen muss, um den "Dienst" zu starten.

**Comment by Kai9555** [comment]
> Das mache ich gerne fertig. Schaue ob ich am Wochenende dazu komme.

👍🏻👍🏻👍🏻

**Comment by Kai9555** [comment]
Mittlerweile ist mein pi zero da. Also wenn du bei Gelegenheit kurz zusammenfassen kannst wie ich unter Pi OS oder dergleichen dein Programm installieren kann :) thx

**Comment by Kai9555** [comment]
Ist es normal das nach "starting server..." nichts weiter passiert? Unter meinem Port 8099 ist mit ipadresse_pi:8099 auch keine Seite erreichbar.

<img width="630" alt="Bildschirmfoto 2022-02-06 um 09 32 58 Kopie" src="https://user-images.githubusercontent.com/56715979/152673643-5cf5b0a4-ae65-4139-abc1-f98beabd6fb8.png">

**Comment by JWThewes** [comment]
Also laut Log ist dann alles ok. Kannst du einmal schauen ob der Server unter http://localhost:8099/groups antwortet. Alternativ unter http://localhost:8090/groups

**Comment by Kai9555** [comment]
Wenn ich http://localhost:8090/groups verwende (obwohl ich in der config den Port auf 8099 geändert habe) dann kommt eine weiße Seite mit "null" als output.

Ich musste den Port ändern, da 8090 bereits vergeben ist.

**Comment by JWThewes** [comment]
Wenn das der Fall ist dann ist alles super. Die Ausgabe unter der genannten URL liefert die Lampen und Gruppen die es auf der Hue Bridge gibt. Darüber kann man dann ein einzelnes Licht (/toggle/light/<LICH-ID>) umschalten.

**Comment by Kai9555** [comment]
Perfekt 👍🏻 Habe es mit Hilfe aus dem Shelly-support Forum geschafft. Mir war leider nicht klar wie ich das Programm starten konnte. Der Rest ist gut beschrieben.

**Comment by JWThewes** [comment]
> Wenn ich http://localhost:8090/groups verwende (obwohl ich in der config den Port auf 8099 geändert habe) dann kommt eine weiße Seite mit "null" als output.
> 
> 
> 
> Ich musste den Port ändern, da 8090 bereits vergeben ist.

Aber dann kommt die Antwort ja mit Sicherheit auch von der Anwendung die auf Port 8090 läuft. Ich muss in den Code schauen warum das nicht klappt. Ich habe meinen lokalen Port auch auf was anderes als den default Port gestellt das funktioniert.
Ich schaue heute Abend nach.

Unter 8090 kommt gar nichts.

**Comment by Kai9555** [comment]
> > Wenn ich http://localhost:8090/groups verwende (obwohl ich in der config den Port auf 8099 geändert habe) dann kommt eine weiße Seite mit "null" als output.
> > Ich musste den Port ändern, da 8090 bereits vergeben ist.
> 
> Aber dann kommt die Antwort ja mit Sicherheit auch von der Anwendung die auf Port 8090 läuft. Ich muss in den Code schauen warum das nicht klappt. Ich habe meinen lokalen Port auch auf was anderes als den default Port gestellt das funktioniert. Ich schaue heute Abend nach.
> 
> Unter 8090 kommt gar nichts.

Ja mit dem angepassten Port 8099 geht es. Danke 👍🏻

**Comment by Kai9555** [comment]
@JWThewes In deiner Anleitung ist ein kleiner Fehler: die beiden letzten Screenshots für den Link der Gruppe Küche sind die falschen.

Andere Frage: Kann ich auch 2 Lampen mit einem Schalter schalten? Wenn ja, kannst du mir bitte sagen wie der Link aussehen muss.

Vielen Dank 

VG Kai

**Comment by JWThewes** [comment]
@Kai9555 Oh danke, die Screenshots korrigiere ich noch. Ich habe mich dagegen entschieden mehrere Lichter über den einen Endpunkt steuerbar zu machen. Grund: das kann Hue auch nicht. Ich müsste also für jedes übergebene Licht die Hue-Bridge aufrufen.
Lösung:
Du kannst in der Hue-Bridge eine Zone anlegen. Diese taucht dann unter Groups auf und du kannst dann über den /toggle/lights/group/<ZONEN_NAME> diese Zone umschalten. Dafür ist dann nur ein Aufruf von hueshelly an die Hue-Bridge notwendig.
Passt das für dich?

Ansonsten bin ich über Fehlerberichte, Probleme oder Anmerkungen jederzeit dankbar.

**Comment by Kai9555** [comment]
Ich konnte es noch nicht testen, aber so wird es gehen. Hintergrund: die Esszimmerlampe (Hue Ensis) ist eine Lampe, die aus 2 LED Streifen besteht und somit natürlich auch nur über einen Lichtschalter geschalten wird.

Danke 👍🏻

**Comment by Kai9555** [comment]
Guten Abend, ich bin nun endlich einmal zum testen gekommen. Alles funktioniert auch hervorragend, nur eine wichtige Sache löst sich mir nicht auf. Immer wenn ich den Schalter betätige, leuchten die Hue Lampen 100%, auch wenn vorher nur 20% eingestellt waren. Ich hoffe ich habe etwas wichtiges übersehen, denn die Lampen sollten sich eigentlich die letzte Einstellung merken. Wie ist es denn bei dir?

Vielen Dank

**Comment by JWThewes** [comment]
Ja ok das ist aktuell "works as designed".
Ich hatte es bei mir genau so vor und habe es deswegen so gebaut.
Ist aber kein Problem.
Wenn du ein neues Issue aufmachst dann baue ich das heute Abend eben um und dann bleiben sie auf der Helligkeit die sie vorher hatten.

**Comment by Kai9555** [comment]
Oh mein Gott ist ja der Hammer! Danke dir

**Comment by Kai9555** [comment]
Ich wollte dir gerade ein Sponsoring für deine Mühe da lassen. Irgendwie fehlt der Button dazu bei dir?
<img width="1314" alt="Bildschirmfoto 2022-02-15 um 09 01 51" src="https://user-images.githubusercontent.com/56715979/154018392-4e698d8d-245a-4216-a6d8-9e6259c9c625.png">
!

**Comment by JWThewes** [comment]
Habe einen Sponsoring Link eingefügt. Hätte ja niemals erwartet das es jemanden gibt der das wirklich nützlich findet. Insofern habe ich sowas gar nicht vorgesehen.
Aber ich freue mich natürlich wenn es für dich funktioniert und dir gefällt. Anpassung mache ich heute fertig.

**Comment by Kai9555** [comment]
Ist ja nicht die Welt ein paar Euro zu sponsoren. Davon wird niemand reich, aber auch nicht arm. Ist eher eine Geste und gehört für mich zum guten Ton 🤟 - Danke
