### ISSUE TITLE
Letzte Einstellung nach Schaltvorgang merken

### ISSUE THREAD

**Issue by Kai9555** [JWThewes/hueshelly#7]
Mit Version 1.0.0 wird mit jedem Betätigen der Taste die Hue-Leuchte auf 100% eingeschaltet. Wir besprochen hier das Ticket für eine Anpassung, um bei einem Schaltvorgang die letzte Einstellung (z.B. 20% Helligkeit) wiederherzustellen.

Danke 💪🏻

**Comment by JWThewes** [comment]
Release 1.1.0 ist da. In der config.json folgendes hinzufügen:  "restorePreviousLightState": true dann wird die vorherige Helligkeit genommen. Bzw. das was die Hue als Default hat.

**Comment by Kai9555** [comment]
Wow super 👍🏻 das ging fix. Es funktioniert 👌🏻
